//! Intel MKL-only Level 3 CBLAS entry points.
//!
//! Unsuffixed symbols use the selected ordinary LP64 or ILP64 `CBlasInt` ABI.
//! Their explicit MKL `*_64` counterparts are in
//! [`super::cblas_level_three_mkl_64`].

use crate::cblas::cblas_types::*;

unsafe extern "C" {
    pub fn cblas_hgemm(
        layout: CBlasLayout,
        transa: CBlasTranspose,
        transb: CBlasTranspose,
        m: CBlasInt,
        n: CBlasInt,
        k: CBlasInt,
        alpha: CBlasF16,
        a: *const CBlasF16,
        lda: CBlasInt,
        b: *const CBlasF16,
        ldb: CBlasInt,
        beta: CBlasF16,
        c: *mut CBlasF16,
        ldc: CBlasInt,
    );

    pub fn cblas_strmm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: CBlasFloat,
        a: *const CBlasFloat,
        lda: CBlasInt,
        b: *const CBlasFloat,
        ldb: CBlasInt,
        beta: CBlasFloat,
        c: *mut CBlasFloat,
        ldc: CBlasInt,
    );
    pub fn cblas_dtrmm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: CBlasDouble,
        a: *const CBlasDouble,
        lda: CBlasInt,
        b: *const CBlasDouble,
        ldb: CBlasInt,
        beta: CBlasDouble,
        c: *mut CBlasDouble,
        ldc: CBlasInt,
    );
    pub fn cblas_ctrmm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: *const CBlasVoid,
        a: *const CBlasVoid,
        lda: CBlasInt,
        b: *const CBlasVoid,
        ldb: CBlasInt,
        beta: *const CBlasVoid,
        c: *mut CBlasVoid,
        ldc: CBlasInt,
    );
    pub fn cblas_ztrmm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: *const CBlasVoid,
        a: *const CBlasVoid,
        lda: CBlasInt,
        b: *const CBlasVoid,
        ldb: CBlasInt,
        beta: *const CBlasVoid,
        c: *mut CBlasVoid,
        ldc: CBlasInt,
    );

    pub fn cblas_strsm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: CBlasFloat,
        a: *const CBlasFloat,
        lda: CBlasInt,
        b: *const CBlasFloat,
        ldb: CBlasInt,
        beta: CBlasFloat,
        c: *mut CBlasFloat,
        ldc: CBlasInt,
    );
    pub fn cblas_dtrsm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: CBlasDouble,
        a: *const CBlasDouble,
        lda: CBlasInt,
        b: *const CBlasDouble,
        ldb: CBlasInt,
        beta: CBlasDouble,
        c: *mut CBlasDouble,
        ldc: CBlasInt,
    );
    pub fn cblas_ctrsm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: *const CBlasVoid,
        a: *const CBlasVoid,
        lda: CBlasInt,
        b: *const CBlasVoid,
        ldb: CBlasInt,
        beta: *const CBlasVoid,
        c: *mut CBlasVoid,
        ldc: CBlasInt,
    );
    pub fn cblas_ztrsm_oop(
        layout: CBlasLayout,
        side: CBlasSide,
        uplo: CBlasUplo,
        transa: CBlasTranspose,
        diag: CBlasDiag,
        m: CBlasInt,
        n: CBlasInt,
        alpha: *const CBlasVoid,
        a: *const CBlasVoid,
        lda: CBlasInt,
        b: *const CBlasVoid,
        ldb: CBlasInt,
        beta: *const CBlasVoid,
        c: *mut CBlasVoid,
        ldc: CBlasInt,
    );
}
